# Generated by Django 6.0 on 2026-03-22 17:17

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saloons', '0020_saloonmapclick_saloonprofileview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingSubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('499.00'), max_digits=8)),
                ('strike_amount', models.DecimalField(decimal_places=2, default=Decimal('999.00'), max_digits=8)),
                ('billing_period', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('interval', models.PositiveSmallIntegerField(default=1)),
                ('trial_days', models.PositiveSmallIntegerField(default=30)),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('razorpay_plan_id', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=120)),
                ('razorpay_subscription_id', models.CharField(blank=True, max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SaloonSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trialing', 'Trial Active'), ('pending_auth', 'Autopay Pending'), ('active', 'Autopay Active'), ('past_due', 'Payment Due'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='trialing', max_length=24)),
                ('trial_started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('trial_ends_at', models.DateTimeField()),
                ('autopay_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('razorpay_plan_id', models.CharField(blank=True, max_length=80)),
                ('razorpay_subscription_id', models.CharField(blank=True, max_length=80)),
                ('razorpay_customer_id', models.CharField(blank=True, max_length=80)),
                ('razorpay_status', models.CharField(blank=True, max_length=40)),
                ('auth_payment_id', models.CharField(blank=True, max_length=80)),
                ('last_payment_id', models.CharField(blank=True, max_length=80)),
                ('last_payment_status', models.CharField(blank=True, max_length=40)),
                ('cancel_at_cycle_end', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='plans.listingsubscriptionplan')),
                ('saloon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='saloons.saloon')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['saloon', 'status'], name='plans_saloo_saloon__c8af38_idx'), models.Index(fields=['razorpay_subscription_id'], name='plans_saloo_razorpa_e07272_idx')],
            },
        ),
    ]
