# Generated by Codex for Razorpay subscription billing history.

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('plans', '0001_initial'),
        ('saloons', '0024_saloon_myfestivo_handoff_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingsubscriptionplan',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('699.00'), max_digits=8),
        ),
        migrations.AlterField(model_name='listingsubscriptionplan', name='razorpay_plan_id', field=models.CharField(blank=True, max_length=250)),
        migrations.AlterField(model_name='saloonsubscription', name='razorpay_plan_id', field=models.CharField(blank=True, max_length=250)),
        migrations.AlterField(model_name='saloonsubscription', name='razorpay_subscription_id', field=models.CharField(blank=True, max_length=250)),
        migrations.AlterField(model_name='saloonsubscription', name='razorpay_customer_id', field=models.CharField(blank=True, max_length=512)),
        migrations.AlterField(model_name='saloonsubscription', name='razorpay_status', field=models.CharField(blank=True, max_length=80)),
        migrations.AlterField(model_name='subscriptionwebhookevent', name='razorpay_subscription_id', field=models.CharField(blank=True, max_length=250)),
        migrations.CreateModel(
            name='SubscriptionPaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('payment_status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], default='pending', max_length=24)),
                ('payment_method', models.CharField(blank=True, max_length=120)),
                ('renewal_type', models.CharField(blank=True, max_length=80)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=250)),
                ('razorpay_subscription_id', models.CharField(blank=True, max_length=250)),
                ('transaction_reference', models.CharField(blank=True, max_length=250)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={'ordering': ['-paid_at', '-id']},
        ),
        migrations.AddField(model_name='saloonsubscription', name='approved_trial_days', field=models.PositiveSmallIntegerField(default=14)),
        migrations.AddField(model_name='saloonsubscription', name='founder_partner_number', field=models.PositiveSmallIntegerField(blank=True, null=True)),
        migrations.AddField(model_name='saloonsubscription', name='grace_period_ends_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='saloonsubscription', name='grace_period_started_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='saloonsubscription', name='is_founder_partner', field=models.BooleanField(default=False)),
        migrations.AddField(model_name='saloonsubscription', name='trial_assigned_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='subscriptionwebhookevent', name='error_message', field=models.TextField(blank=True)),
        migrations.AddField(model_name='subscriptionwebhookevent', name='idempotency_key', field=models.CharField(blank=True, max_length=250, null=True, unique=True)),
        migrations.AddField(model_name='subscriptionwebhookevent', name='processing_status', field=models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('duplicate', 'Duplicate'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='pending', max_length=24)),
        migrations.AddField(model_name='subscriptionwebhookevent', name='verification_status', field=models.CharField(default='unverified', max_length=40)),
        migrations.AddField(model_name='subscriptionwebhookevent', name='webhook_signature', field=models.CharField(blank=True, max_length=512)),
        migrations.AddField(model_name='subscriptionwebhookevent', name='webhook_timestamp', field=models.CharField(blank=True, max_length=80)),
        migrations.AddIndex(model_name='subscriptionwebhookevent', index=models.Index(fields=['event_name', 'processing_status'], name='plans_subsc_event_n_9e7571_idx')),
        migrations.AddIndex(model_name='subscriptionwebhookevent', index=models.Index(fields=['razorpay_subscription_id'], name='plans_subsc_razorpa_ee3892_idx')),
        migrations.AddField(model_name='subscriptionpaymenthistory', name='plan', field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_history', to='plans.listingsubscriptionplan')),
        migrations.AddField(model_name='subscriptionpaymenthistory', name='saloon', field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to='saloons.saloon')),
        migrations.AddField(model_name='subscriptionpaymenthistory', name='subscription', field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='plans.saloonsubscription')),
        migrations.AddIndex(model_name='subscriptionpaymenthistory', index=models.Index(fields=['saloon', 'payment_status'], name='plans_subsc_saloon__48fd15_idx')),
        migrations.AddIndex(model_name='subscriptionpaymenthistory', index=models.Index(fields=['razorpay_subscription_id'], name='plans_subsc_razorpa_3690d3_idx')),
        migrations.AddIndex(model_name='subscriptionpaymenthistory', index=models.Index(fields=['razorpay_payment_id'], name='plans_subsc_razorpa_fc219e_idx')),
    ]