# Generated by Django 6.0 on 2025-12-22 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saloons', '0011_alter_saloon_registration_step_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('image', models.ImageField(upload_to='services/images/')),
                ('is_visible', models.BooleanField(default=True, help_text='Temporary availability toggle')),
                ('is_active', models.BooleanField(default=False, help_text='Activated only after saloon approval')),
                ('is_promoted', models.BooleanField(default=False)),
                ('added_during_onboarding', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('saloon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='saloons.saloon')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='services.servicecategory')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category'], name='services_se_categor_7ca2f8_idx'), models.Index(fields=['is_promoted'], name='services_se_is_prom_5fa4b7_idx'), models.Index(fields=['is_visible'], name='services_se_is_visi_381563_idx')],
            },
        ),
    ]
