# Generated by Django 6.0 on 2025-12-22 07:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saloons', '0011_alter_saloon_registration_step_and_more'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='created_by_saloon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_service_categories', to='saloons.saloon'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Service becomes active after saloon approval'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_promoted',
            field=models.BooleanField(default=False, help_text='Boost service visibility on platform'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Temporarily hide service from public view'),
        ),
        migrations.AlterField(
            model_name='service',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional discounted price', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Inactive categories won't appear in suggestions"),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_active'], name='services_se_is_acti_91b7ea_idx'),
        ),
    ]
