# Generated by Django 6.0 on 2026-01-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicecategory_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag for undo support'),
        ),
    ]
