# Generated by Django 6.0 on 2026-01-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saloons', '0012_alter_saloon_approval_status'),
        ('services', '0003_service_deleted_at_service_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete for undo & recovery'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_promoted',
            field=models.BooleanField(default=False, help_text='Boost service visibility'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_deleted'], name='services_se_is_dele_f635ae_idx'),
        ),
    ]
