# Generated by Django 6.0 on 2026-02-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_service_is_deleted_alter_service_is_promoted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='is_approved',
            field=models.BooleanField(
                default=True,
                help_text='Only approved categories appear to buyers'
            ),
            preserve_default=False,
        ),
    ]
