# Generated by Django 6.0 on 2026-02-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_servicecategory_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Only approved categories appear to buyers'),
        ),
    ]
