# Generated by Django 6.0 on 2026-03-17 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_maincategory_icon_image_remove_icon_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_events', to='services.service')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['service', 'created_at'], name='services_se_service_035c70_idx')],
            },
        ),
    ]
