# Generated by Django 6.0 on 2026-09-21 08:49

from django.db import migrations, models


def activate_existing_staff(apps, schema_editor):
    StaffProfile = apps.get_model('staffpanel', 'StaffProfile')
    StaffProfile.objects.filter(status='pending').update(status='active')


class Migration(migrations.Migration):

    dependencies = [
        ('staffpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='invite_code_display',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending invite'), ('active', 'Active'), ('suspended', 'Suspended'), ('blocked', 'Blocked'), ('removed', 'Removed')], default='pending', max_length=24),
        ),
        migrations.RunPython(activate_existing_staff, migrations.RunPython.noop),
    ]
