# Generated by Django 6.0 on 2026-03-25 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='favoritesaloon',
            new_name='public_favo_user_id_ec3d94_idx',
            old_name='public_favo_user_id_2655f9_idx',
        ),
        migrations.RenameIndex(
            model_name='favoritesaloon',
            new_name='public_favo_saloon__a6b402_idx',
            old_name='public_favo_saloon__4a0f83_idx',
        ),
    ]
