# Generated by Django 6.0 on 2025-12-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saloons', '0002_trusteddevice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saloon',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='saloon',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
