# Generated by Django 6.0 on 2025-12-18 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saloons', '0003_remove_saloon_is_approved_saloon_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='saloon',
            name='registration_step',
            field=models.PositiveSmallIntegerField(default=1, help_text='Current registration step'),
        ),
        migrations.CreateModel(
            name='SaloonBankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('saloon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_detail', to='saloons.saloon')),
            ],
        ),
        migrations.CreateModel(
            name='SaloonIDVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proof', models.FileField(upload_to='saloons/id/')),
                ('id_number', models.CharField(max_length=100)),
                ('saloon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='id_verification', to='saloons.saloon')),
            ],
        ),
        migrations.CreateModel(
            name='SaloonImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='saloons/images/')),
                ('image_type', models.CharField(choices=[('front', 'Front'), ('inside', 'Inside'), ('banner', 'Banner'), ('clean', 'Clean Area')], max_length=20)),
                ('saloon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='saloons.saloon')),
            ],
        ),
        migrations.CreateModel(
            name='SaloonProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_full_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('unisex', 'Unisex')], max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=255)),
                ('google_map_link', models.URLField(blank=True, null=True)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('operating_days', models.JSONField(help_text='List of operating days')),
                ('saloon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='saloons.saloon')),
            ],
        ),
        migrations.CreateModel(
            name='SaloonRejectionReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(help_text='Example: front_image, id_proof, service_1_price', max_length=100)),
                ('message', models.CharField(help_text='Example: Image is blurry', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('saloon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejection_reasons', to='saloons.saloon')),
            ],
        ),
        migrations.CreateModel(
            name='SaloonService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='saloons/services/')),
                ('added_during_onboarding', models.BooleanField(default=True)),
                ('saloon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='saloons.saloon')),
            ],
        ),
    ]
