# Generated by Django 6.0 on 2025-12-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saloons', '0004_saloon_registration_step_saloonbankdetail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saloonprofile',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saloonprofile',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saloonprofile',
            name='operating_days',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
