# Generated by Django 6.0 on 2025-12-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saloons', '0005_alter_saloonprofile_closing_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saloon',
            name='saloon_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
