# Generated by Django 6.0 on 2025-12-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saloons', '0006_saloon_saloon_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saloon',
            name='saloon_name',
        ),
        migrations.AddField(
            model_name='saloonprofile',
            name='saloon_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
