# Generated by Django 6.0 on 2025-12-20 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saloons', '0007_remove_saloon_saloon_name_saloonprofile_saloon_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saloonidverification',
            name='saloon',
        ),
        migrations.RemoveField(
            model_name='saloonimage',
            name='saloon',
        ),
        migrations.AlterField(
            model_name='saloonrejectionreason',
            name='field_key',
            field=models.CharField(help_text='Example: inside_image_1, owner_id_proof', max_length=100),
        ),
        migrations.CreateModel(
            name='SaloonVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id_proof', models.FileField(upload_to='saloons/verification/id/')),
                ('owner_id_number', models.CharField(max_length=100)),
                ('inside_image_1', models.ImageField(upload_to='saloons/verification/inside/')),
                ('inside_image_2', models.ImageField(blank=True, null=True, upload_to='saloons/verification/inside/')),
                ('inside_image_3', models.ImageField(blank=True, null=True, upload_to='saloons/verification/inside/')),
                ('outside_image_1', models.ImageField(upload_to='saloons/verification/outside/')),
                ('outside_image_2', models.ImageField(blank=True, null=True, upload_to='saloons/verification/outside/')),
                ('outside_image_3', models.ImageField(blank=True, null=True, upload_to='saloons/verification/outside/')),
                ('account_holder_name', models.CharField(blank=True, max_length=255)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('ifsc_code', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('saloon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='saloons.saloon')),
            ],
        ),
        migrations.DeleteModel(
            name='SaloonBankDetail',
        ),
        migrations.DeleteModel(
            name='SaloonIDVerification',
        ),
        migrations.DeleteModel(
            name='SaloonImage',
        ),
    ]
