# Generated by Django 6.0 on 2025-12-21 08:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saloons', '0008_remove_saloonidverification_saloon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saloon',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='saloons/banner/'),
        ),
        migrations.AddField(
            model_name='saloonservice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saloonservice',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
