# Generated by Django 6.0 on 2025-12-21 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saloons', '0009_saloon_banner_image_saloonservice_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedSaloon',
            fields=[
            ],
            options={
                'verbose_name': 'Approved Saloon',
                'verbose_name_plural': 'Approved Saloons',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('saloons.saloon',),
        ),
        migrations.CreateModel(
            name='SaloonApprovalQueue',
            fields=[
            ],
            options={
                'verbose_name': 'Manage Approval',
                'verbose_name_plural': 'Manage Approvals',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('saloons.saloon',),
        ),
    ]
