# Generated by Django 6.0 on 2025-12-22 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saloons', '0010_approvedsaloon_saloonapprovalqueue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saloon',
            name='registration_step',
            field=models.PositiveSmallIntegerField(default=1, help_text='Current onboarding step'),
        ),
        migrations.AlterField(
            model_name='saloonrejectionreason',
            name='field_key',
            field=models.CharField(help_text='Example: banner_image, inside_image_1', max_length=100),
        ),
        migrations.AlterField(
            model_name='saloonrejectionreason',
            name='message',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='SaloonService',
        ),
    ]
