# Generated by Django 6.0 on 2025-12-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saloons', '0011_alter_saloon_registration_step_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saloon',
            name='approval_status',
            field=models.CharField(choices=[('Submitting', 'Submitting'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='Submitting', max_length=20),
        ),
    ]
