# Generated by Django 6.0 on 2026-02-04 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saloons', '0012_alter_saloon_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='saloonprofile',
            name='about',
            field=models.TextField(blank=True),
        ),
    ]
