# Generated by Django 6.0 on 2026-02-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saloons', '0014_gallerypost_gallerymedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerypost',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
