# Generated by Django 6.0 on 2026-03-15 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saloons', '0016_saloonprofile_latitude_saloonprofile_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='saloonprofile',
            name='whatsapp_prefill_template',
            field=models.TextField(blank=True, help_text='Optional WhatsApp message template. Use {salon_name} and {services} placeholders.'),
        ),
    ]
