# Generated by Django 6.0 on 2026-03-16 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saloons', '0017_saloonprofile_whatsapp_prefill_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaloonReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=120)),
                ('rating', models.PositiveSmallIntegerField()),
                ('review_text', models.TextField()),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('saloon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='saloons.saloon')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
