# Generated by Django 6.0 on 2026-03-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saloons', '0018_saloonreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='saloonreview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
