# Generated by Django 6.0 on 2026-03-17 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saloons', '0019_saloonreview_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaloonMapClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('saloon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_click_events', to='saloons.saloon')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['saloon', 'created_at'], name='saloons_sal_saloon__0fb444_idx')],
            },
        ),
        migrations.CreateModel(
            name='SaloonProfileView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('saloon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_view_events', to='saloons.saloon')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['saloon', 'created_at'], name='saloons_sal_saloon__fe0499_idx')],
            },
        ),
    ]
