# Generated by Django 6.0 on 2026-09-23 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saloons', '0024_saloon_myfestivo_handoff_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerypost',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gallerypost',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gallerypost',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_gallery_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gallerypost',
            name='moderation_reason',
            field=models.TextField(blank=True),
        ),
    ]
