# Generated by Django 6.0 on 2026-10-03 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saloons', '0025_gallerypost_is_hidden_gallerypost_moderated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='saloon',
            name='is_test_saloon',
            field=models.BooleanField(default=False, help_text='Internal launch/test listing. It can appear publicly but never consumes founder partner slots.'),
        ),
        migrations.AddField(
            model_name='saloon',
            name='test_saloon_converted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saloon',
            name='test_saloon_hidden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saloon',
            name='test_saloon_marked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saloon',
            name='test_saloon_marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_saloons_marked', to=settings.AUTH_USER_MODEL),
        ),
    ]
